/*
 * This source file was generated by the Gradle 'init' task
 */
package curso.apps.moviles;

public class App {
    public String getGreeting() {
        return "Buen dia!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
